[package]
name = "zepto"
version = "0.1.0"
authors = ["Robert Rusch <rusch@mit.edu>"]
edition = "2018"

[dependencies]
failure = "*"
log = "*"
stderrlog = "*"
termion = "*"
tui = "*"
rand = "*"
unicode-width = "*"
